name: Update SolidResource Feeds

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: write  # allow this workflow to commit changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure feeds directory exists
        run: mkdir -p feeds

      - name: Generate Finviz feed
        run: python finviz_rss.py --config config.yaml --out feeds/finviz_movers.xml

      - name: Generate Premarket feed (fallback-hardened)
        run: |
          python premarket_rss.py --config config.yaml --out feeds/premarket_movers.xml || true

      - name: Combine feeds (optional)
        run: |
          python combine_feeds.py --out feeds/all.xml feeds/premarket_movers.xml feeds/finviz_movers.xml || true

      - name: Commit & push changes
        run: |
          git config user.name "solid-bot"
          git config user.email "bot@solidresource.com"
          git add feeds/*.xml || true
          git diff --quiet && echo "No changes to commit." || git commit -m "Update feeds via GitHub Actions"
          git push
