name: Build & Deploy Feeds to Pages

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feeds
        run: |
          mkdir -p feeds
          python finviz_rss.py --config config.yaml --out feeds/finviz_movers.xml
          python premarket_rss.py --config config.yaml --out feeds/premarket_movers.xml || true
          python combine_feeds.py --out feeds/all.xml feeds/premarket_movers.xml feeds/finviz_movers.xml || true
          # Optional: add a simple index so the root isn't blank
          echo "<h1>SolidResource Feeds</h1><ul><li><a href='feeds/premarket_movers.xml'>Premarket</a></li><li><a href='feeds/finviz_movers.xml'>Finviz Intraday</a></li><li><a href='feeds/all.xml'>Combined</a></li></ul>" > index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Publish the WHOLE repo root so /feeds/*.xml are directly accessible
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
