name: Update SolidResource Feeds
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python finviz_rss.py --config config.yaml --out feeds/finviz_movers.xml
      - run: python premarket_rss.py --config config.yaml --out feeds/premarket_movers.xml || true
      - name: Commit & push
        run: |
          git config user.name "solid-bot"
          git config user.email "bot@solidresource.com"
          git add feeds/finviz_movers.xml feeds/premarket_movers.xml || true
          git diff --quiet || (git commit -m "Update feeds" && git push)
